services:
  api:
    build: ./api
    container_name: api
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g    
    cpus: 2.5            
    environment:
      - DB_HOST=165.232.42.130
      - DB_USER=admin
      - DB_PASSWORD=admin@2025
      - DB_NAME=project
    networks:
      - project       

  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "8081:80"
    networks:
      - project
    mem_limit: 64M
    cpus: 0.2


  loadbalancer:
    image: nginx:latest
    container_name: loadbalancer
    restart: unless-stopped
    ports:
      - "5001:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g      
    cpus: 1.0            
    networks:
      - project

  lpar2rrd-docker-agent:
    image: xorux/lpar2rrd-docker-agent
    container_name: lpar2rrd-docker-agent
    hostname: "mitigated-server"
    restart: always 
    environment:
      - XORMON=167.71.118.73
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - project
    mem_limit: 128M
    cpus: 0.2

networks:
  project:
    driver: bridge