
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"     # HTTP UI
      # - "9443:9443"   # (optional) HTTPS UI if you want it
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/mmintah/Desktop/virtualenv/opt/portainer/data:/data